# Generated by Django 5.1.6 on 2025-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('projects', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stakeholders',
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='projects', to='contacts.contact'),
        ),
    ]
